image: fedora:rawhide

variables:
  DEPENDENCIES: dbus-glib-devel pam-devel polkit-devel
                gtk-doc meson intltool autoconf automake libtool
                gcc gcc-c++ glibc-devel make python3-dbusmock python3-libpamtest
  DEPENDENCIES_STABLE: $DEPENDENCIES libfprint-devel
  DEPENDENCIES_DEV: $DEPENDENCIES git
  # Sync'ed up with https://gitlab.freedesktop.org/libfprint/libfprint/blob/master/.gitlab-ci.yml
  # and stripped down to remove dependencies that are not strictly needed
  DEPENDENCIES_LIBFPRINT: libgusb-devel glib2-devel meson
                          gcc gcc-c++ glibc-devel
                          gobject-introspection-devel python3-cairo python3-gobject

build_stable:
  # FIXME: Stable builds will fail until libfprintv 2 reaches rawhide
  allow_failure: true
  before_script:
    - dnf update -y --nogpgcheck && dnf install -y --nogpgcheck $DEPENDENCIES_STABLE
  script:
    - ./autogen.sh --disable-dependency-tracking
    - make
    - make install

build_dev:
  before_script:
    - dnf update -y --nogpgcheck && dnf install -y --nogpgcheck $DEPENDENCIES_LIBFPRINT $DEPENDENCIES_DEV
    - git clone https://gitlab.freedesktop.org/libfprint/libfprint.git
    - cd libfprint
    - meson . _build --prefix=/usr -Ddrivers=virtual_image -Ddoc=false
    - ninja -C _build
    - ninja -C _build install
    - cd ..
    # So we don't get error about this libfprint file
    - echo "libfprint/demo/gtk-libfprint-test.ui" >> po/POTFILES.skip
  script:
    - ./autogen.sh --disable-dependency-tracking
    - make
    - make install

test_dev:
  stage: test
  before_script:
    - dnf update -y --nogpgcheck && dnf install -y --nogpgcheck $DEPENDENCIES_LIBFPRINT $DEPENDENCIES_DEV
    - git clone https://gitlab.freedesktop.org/libfprint/libfprint.git
    - cd libfprint
    - meson . _build --prefix=/usr -Ddrivers=virtual_image -Ddoc=false
    - ninja -C _build
    - ninja -C _build install
    - cd ..
    # So we don't get error about this libfprint file
    - echo "libfprint/demo/gtk-libfprint-test.ui" >> po/POTFILES.skip
  script:
    - ./autogen.sh --disable-dependency-tracking
    - make
    - make check
  artifacts:
    name: log
    when: always
    paths:
      - tests/*.log
