image: fedora:rawhide

include:
  - project: 'libfprint/libfprint'
    ref: master
    file: '/.gitlab-ci/libfprint-templates.yaml'

variables:
  DEPENDENCIES: dbus-glib-devel pam-devel polkit-devel
                gtk-doc meson gettext gcovr
                gcc gcc-c++ glibc-devel python3-dbusmock python3-libpamtest systemd-devel
  DEPENDENCIES_STABLE: $DEPENDENCIES libfprint-devel
  DEPENDENCIES_DEV: $DEPENDENCIES git

.install_libfprint_dev: &install_libfprint_dev
  before_script:
    - dnf update -y --nogpgcheck && dnf install -y --nogpgcheck $LIBFPRINT_DEPENDENCIES $DEPENDENCIES_DEV
    - git clone https://gitlab.freedesktop.org/libfprint/libfprint.git
    - cd libfprint
    - meson . _build --prefix=/usr -Ddrivers=virtual_image -Ddoc=false
    - ninja -C _build
    - ninja -C _build install
    - cd ..
    # So we don't get error about this libfprint file
    - echo "libfprint/demo/gtk-libfprint-test.ui" >> po/POTFILES.skip

build_stable:
  # FIXME: Stable builds will fail until libfprintv 2 reaches rawhide
  allow_failure: true
  before_script:
    - dnf update -y --nogpgcheck && dnf install -y --nogpgcheck $DEPENDENCIES_STABLE
  script:
    - meson _build
    - ninja -C _build -v
    - ninja -C _build -v install

build_dev:
  <<: *install_libfprint_dev
  script:
    - meson _build --werror -Dgtk_doc=true
    - ninja -C _build -v
    - ninja -C _build -v install
  artifacts:
    name: log
    when: on_failure
    paths:
      - _build/meson-logs/*.txt

test_dev:
  stage: test
  <<: *install_libfprint_dev
  script:
    - meson _build -Db_coverage=true
    - meson test -C _build --verbose --no-stdsplit --timeout-multiplier 3
    - ninja -C _build coverage
    - cat _build/meson-logs/coverage.txt
  artifacts:
    name: log-and-coverage
    when: always
    paths:
      - _build/meson-logs
